=begin
#Topological Inventory

#Topological Inventory

OpenAPI spec version: 0.1.0
Contact: you@your-company.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'date'

module TopologicalInventoryApiClient
  class Container
    attr_accessor :archived_at

    # ID of the resource
    attr_accessor :container_group_id

    # ID of the resource
    attr_accessor :container_image_id

    attr_accessor :cpu_limit

    attr_accessor :cpu_request

    attr_accessor :created_at

    # ID of the resource
    attr_accessor :id

    attr_accessor :memory_limit

    attr_accessor :memory_request

    attr_accessor :name

    attr_accessor :updated_at

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'archived_at' => :'archived_at',
        :'container_group_id' => :'container_group_id',
        :'container_image_id' => :'container_image_id',
        :'cpu_limit' => :'cpu_limit',
        :'cpu_request' => :'cpu_request',
        :'created_at' => :'created_at',
        :'id' => :'id',
        :'memory_limit' => :'memory_limit',
        :'memory_request' => :'memory_request',
        :'name' => :'name',
        :'updated_at' => :'updated_at'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'archived_at' => :'DateTime',
        :'container_group_id' => :'String',
        :'container_image_id' => :'String',
        :'cpu_limit' => :'Float',
        :'cpu_request' => :'Float',
        :'created_at' => :'DateTime',
        :'id' => :'String',
        :'memory_limit' => :'Integer',
        :'memory_request' => :'Integer',
        :'name' => :'String',
        :'updated_at' => :'DateTime'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'archived_at')
        self.archived_at = attributes[:'archived_at']
      end

      if attributes.has_key?(:'container_group_id')
        self.container_group_id = attributes[:'container_group_id']
      end

      if attributes.has_key?(:'container_image_id')
        self.container_image_id = attributes[:'container_image_id']
      end

      if attributes.has_key?(:'cpu_limit')
        self.cpu_limit = attributes[:'cpu_limit']
      end

      if attributes.has_key?(:'cpu_request')
        self.cpu_request = attributes[:'cpu_request']
      end

      if attributes.has_key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.has_key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.has_key?(:'memory_limit')
        self.memory_limit = attributes[:'memory_limit']
      end

      if attributes.has_key?(:'memory_request')
        self.memory_request = attributes[:'memory_request']
      end

      if attributes.has_key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.has_key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if !@container_group_id.nil? && @container_group_id !~ Regexp.new(/^\d+$/)
        invalid_properties.push('invalid value for "container_group_id", must conform to the pattern /^\d+$/.')
      end

      if !@container_image_id.nil? && @container_image_id !~ Regexp.new(/^\d+$/)
        invalid_properties.push('invalid value for "container_image_id", must conform to the pattern /^\d+$/.')
      end

      if !@id.nil? && @id !~ Regexp.new(/^\d+$/)
        invalid_properties.push('invalid value for "id", must conform to the pattern /^\d+$/.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if !@container_group_id.nil? && @container_group_id !~ Regexp.new(/^\d+$/)
      return false if !@container_image_id.nil? && @container_image_id !~ Regexp.new(/^\d+$/)
      return false if !@id.nil? && @id !~ Regexp.new(/^\d+$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] container_group_id Value to be assigned
    def container_group_id=(container_group_id)
      if !container_group_id.nil? && container_group_id !~ Regexp.new(/^\d+$/)
        fail ArgumentError, 'invalid value for "container_group_id", must conform to the pattern /^\d+$/.'
      end

      @container_group_id = container_group_id
    end

    # Custom attribute writer method with validation
    # @param [Object] container_image_id Value to be assigned
    def container_image_id=(container_image_id)
      if !container_image_id.nil? && container_image_id !~ Regexp.new(/^\d+$/)
        fail ArgumentError, 'invalid value for "container_image_id", must conform to the pattern /^\d+$/.'
      end

      @container_image_id = container_image_id
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if !id.nil? && id !~ Regexp.new(/^\d+$/)
        fail ArgumentError, 'invalid value for "id", must conform to the pattern /^\d+$/.'
      end

      @id = id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          archived_at == o.archived_at &&
          container_group_id == o.container_group_id &&
          container_image_id == o.container_image_id &&
          cpu_limit == o.cpu_limit &&
          cpu_request == o.cpu_request &&
          created_at == o.created_at &&
          id == o.id &&
          memory_limit == o.memory_limit &&
          memory_request == o.memory_request &&
          name == o.name &&
          updated_at == o.updated_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [archived_at, container_group_id, container_image_id, cpu_limit, cpu_request, created_at, id, memory_limit, memory_request, name, updated_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = TopologicalInventoryApiClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
