=begin
#Topological Inventory

#Topological Inventory

OpenAPI spec version: 0.1.0
Contact: you@your-company.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'date'

module TopologicalInventoryApiClient
  class Endpoint
    # Optional X.509 Certificate Authority
    attr_accessor :certificate_authority

    attr_accessor :created_at

    attr_accessor :default

    # URI host component
    attr_accessor :host

    # ID of the resource
    attr_accessor :id

    # URI path component
    attr_accessor :path

    # URI port component
    attr_accessor :port

    attr_accessor :role

    # URI scheme component
    attr_accessor :scheme

    # ID of the resource
    attr_accessor :source_id

    # ID of the resource
    attr_accessor :tenant_id

    attr_accessor :updated_at

    # Should SSL be verified
    attr_accessor :verify_ssl

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'certificate_authority' => :'certificate_authority',
        :'created_at' => :'created_at',
        :'default' => :'default',
        :'host' => :'host',
        :'id' => :'id',
        :'path' => :'path',
        :'port' => :'port',
        :'role' => :'role',
        :'scheme' => :'scheme',
        :'source_id' => :'source_id',
        :'tenant_id' => :'tenant_id',
        :'updated_at' => :'updated_at',
        :'verify_ssl' => :'verify_ssl'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'certificate_authority' => :'String',
        :'created_at' => :'DateTime',
        :'default' => :'BOOLEAN',
        :'host' => :'String',
        :'id' => :'String',
        :'path' => :'String',
        :'port' => :'Integer',
        :'role' => :'String',
        :'scheme' => :'String',
        :'source_id' => :'String',
        :'tenant_id' => :'String',
        :'updated_at' => :'DateTime',
        :'verify_ssl' => :'BOOLEAN'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'certificate_authority')
        self.certificate_authority = attributes[:'certificate_authority']
      end

      if attributes.has_key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.has_key?(:'default')
        self.default = attributes[:'default']
      end

      if attributes.has_key?(:'host')
        self.host = attributes[:'host']
      end

      if attributes.has_key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.has_key?(:'path')
        self.path = attributes[:'path']
      end

      if attributes.has_key?(:'port')
        self.port = attributes[:'port']
      end

      if attributes.has_key?(:'role')
        self.role = attributes[:'role']
      end

      if attributes.has_key?(:'scheme')
        self.scheme = attributes[:'scheme']
      end

      if attributes.has_key?(:'source_id')
        self.source_id = attributes[:'source_id']
      end

      if attributes.has_key?(:'tenant_id')
        self.tenant_id = attributes[:'tenant_id']
      end

      if attributes.has_key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end

      if attributes.has_key?(:'verify_ssl')
        self.verify_ssl = attributes[:'verify_ssl']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if !@id.nil? && @id !~ Regexp.new(/^\d+$/)
        invalid_properties.push('invalid value for "id", must conform to the pattern /^\d+$/.')
      end

      if !@source_id.nil? && @source_id !~ Regexp.new(/^\d+$/)
        invalid_properties.push('invalid value for "source_id", must conform to the pattern /^\d+$/.')
      end

      if !@tenant_id.nil? && @tenant_id !~ Regexp.new(/^\d+$/)
        invalid_properties.push('invalid value for "tenant_id", must conform to the pattern /^\d+$/.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if !@id.nil? && @id !~ Regexp.new(/^\d+$/)
      return false if !@source_id.nil? && @source_id !~ Regexp.new(/^\d+$/)
      return false if !@tenant_id.nil? && @tenant_id !~ Regexp.new(/^\d+$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if !id.nil? && id !~ Regexp.new(/^\d+$/)
        fail ArgumentError, 'invalid value for "id", must conform to the pattern /^\d+$/.'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] source_id Value to be assigned
    def source_id=(source_id)
      if !source_id.nil? && source_id !~ Regexp.new(/^\d+$/)
        fail ArgumentError, 'invalid value for "source_id", must conform to the pattern /^\d+$/.'
      end

      @source_id = source_id
    end

    # Custom attribute writer method with validation
    # @param [Object] tenant_id Value to be assigned
    def tenant_id=(tenant_id)
      if !tenant_id.nil? && tenant_id !~ Regexp.new(/^\d+$/)
        fail ArgumentError, 'invalid value for "tenant_id", must conform to the pattern /^\d+$/.'
      end

      @tenant_id = tenant_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          certificate_authority == o.certificate_authority &&
          created_at == o.created_at &&
          default == o.default &&
          host == o.host &&
          id == o.id &&
          path == o.path &&
          port == o.port &&
          role == o.role &&
          scheme == o.scheme &&
          source_id == o.source_id &&
          tenant_id == o.tenant_id &&
          updated_at == o.updated_at &&
          verify_ssl == o.verify_ssl
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [certificate_authority, created_at, default, host, id, path, port, role, scheme, source_id, tenant_id, updated_at, verify_ssl].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = TopologicalInventoryApiClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
